import turtle
import time
import math

t = turtle.Turtle()
t.shape("turtle")
t.color("red")
t.speed(0)
t.stamp()
move = 30
for _ in range(12):
    t.penup()
    t.forward(50)
    t.pendown()
    t.forward(25)
    t.penup()
    t.forward(15)
    t.stamp()
    t.home()
    t.right(move)
    move += 30
while True:
    t.home()
    second = time.time() % 60
    t.pendown()
    t.color("black")
    t.setheading((second - 15) * 60)
    t.forward(75)
    t.fillcolor("black")
    t.right(90)
    t.begin_fill()
    t.forward(10)
    t.left(120)
    t.forward(20)
    t.left(120)
    t.forward(20)
    t.left(90)
    t.end_fill()
    t.penup()
    t.home()
    time.sleep(1)
    t.forward(10)
    t.pendown()
    t.setheading((second - 15) * 60)
    t.color("white")
    t.forward(75)
    t.fillcolor("white")
    t.right(90)
    t.begin_fill()
    t.forward(10)
    t.left(120)
    t.forward(20)
    t.left(120)
    t.forward(20)
    t.left(90)
    t.end_fill()
    t.penup()
    t.home()